apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-logger
  namespace: random-logger
  labels:
    app: random-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-logger
  template:
    metadata:
      labels:
        app: random-logger
    spec:
      containers:
        - name: random-logger
          image: devlopesbernardo/random-logger:2.0